### ISSUE TITLE
Privacy consideration: GDPR

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/secure-payment-confirmation#109]
Hi all,

Regarding the "privacy considerations" part of the SPC spec, please note this discussion happening in the WebAuthn repo:
 https://github.com/w3c/webauthn/issues/1656

And in particular:
 https://github.com/w3c/webauthn/issues/1656#issuecomment-891224247

This area is new to me. I do not yet have a good understanding of what, if anything, we need to do. I am flagging this for discussion.

Regarding issue #84, it is probably easier for a payment service provider / relying party to communicate sharing of information rather than the browser. Perhaps this strengthens the case not to have native enrollment browser UX.

**Comment by arshadnoor** [comment]
> This area is new to me. I do not yet have a good understanding of what, if anything, we need to do. I am flagging this for discussion.

Unless there are people who are legally qualified to speak authoritatively on the matter, I do not believe we (technologists) have the ability to make a decision on this matter, Ian (@ianbjacobs).

I only brought it up in the WebAuthn forum because one of our (StrongKey) businesses is data-protection for compliance with regulations such as PCI-DSS, GDPR, CCPA, etc. Some modules in our product focus on technical controls necessary to comply with specific requirements of such regulations; that's how I realized that it could raise a legal issue. This is something that must be addressed by the attorneys at Merchants, AISP/PISP/PSPs and ASPSPs.

If it is helpful at all, here is a presentation on _technical controls_ for GDPR (that _we_ focus on). With specific reference to slides 10-13 on _Consent_, the assumptions we make with those FIDO digital signatures are that Consumers are interacting _directly_ with the RP (aka Data Controller in GDPR parlance) - and not in an iframe.

[StrongKey-GDPR-Seminar-May2019-v2.pdf](https://github.com/w3c/secure-payment-confirmation/files/7017651/StrongKey-GDPR-Seminar-May2019-v2.pdf)

While it should be possible to comply with legal regulations as defined in [WebAuthn-1656](https://github.com/w3c/webauthn/issues/1656) (having the browser provide standardized UX for _Data Controllers_ to make all RP disclosures and point to RP policies, etc. before creating a new FIDO credential) we would stray far from the technical capability of FIDO into business/legal requirements that are **guaranteed** to change; this is why PKI is what/where it is today: unable to solve the business problems it was originally intended for.

Do we really want to go down this path again with FIDO?

(Apologies to those who are tired of hearing me [repeat](https://github.com/w3c/webauthn/issues/1565#issuecomment-880221109) this).

**Comment by arshadnoor** [comment]
Just realized there was an updated version of the GDPR deck from September 2019 with a couple of updated slides (Nos. 25 and 29).

[StrongKey-GDPR-Seminar-September2019-v3.pdf](https://github.com/w3c/secure-payment-confirmation/files/7023034/StrongKey-GDPR-Seminar-September2019-v3.pdf)

**Comment by ianbjacobs** [comment]
In light of the more specific issue https://github.com/w3c/secure-payment-confirmation/issues/172
I am going to close this one. We can open more specific issues (analogous to 172) if needed.
