### ISSUE TITLE
Clarify cardinality between PaymentCredential and payment instruments

### ISSUE THREAD

**Issue by danyao** [w3c/secure-payment-confirmation#13]
Arguments for 1 credential for many instruments:

-  The bank really only wants to authenticate the person. Having 1 credential that works across multiple instruments and possibly even the bank account login is more convenient for the user, as they only need to enroll once.

Arguments for 1 credential for 1 instrument:

- Sharing a credential mixes security domains. This is especially true when sharing between login and payment.

Next step is to try to enumerate attack vectors for sharing credential.

**Comment by adrianhopebailie** [comment]
Also, a single user may have multiple credentials (one on each authenticator/end user device). In reality we'd need to support a many-to-many relationship between credentials and instruments.

**Comment by erhardbrand** [comment]
Supporting multiple instruments per credential would definitely be beneficial.

This does bring to mind cases where a single instrument has to be removed from an existing credential (e.g. card lost, card expired).

While the current WebAuthn convention is for the RP to simply delete the user<->credentials link server side to remove the entire credential, the ability to remove a single instrument from an existing credential could help prevent re-registration if a single instrument is no longer active.

In order to not rely on new API's, a suggestion:
From: https://github.com/rsolomakhin/secure-payment-confirmation#querying-a-credential

**Querying a credential**
```
const publicKeyCredentialRequestOptions = {
  challenge,
  allowCredentials: [{
    id: Uint8Array.from(credentialId, c => c.charCodeAt(0)),
    type,
    transports,
    instruments // Array of linked instruments
  }],
  timeout,
};

const credential = await navigator.credentials.get({
  publicKey: publicKeyCredentialRequestOptions
});

// Look up on displayName (or perhaps new ID) and remove instrument
credential.instruments.forEach(instrument => {
    if (instrument.displayName === 'Mastercard····4444') {
        instrument.remove();
    }
});
```

**Comment by ianbjacobs** [comment]
See related email:
https://lists.w3.org/Archives/Public/public-payments-wg/2021May/0016.html

**Comment by ianbjacobs** [comment]
See discussion from 27 May: 
 https://www.w3.org/2021/05/27-wpwg-minutes#t04

@stephenmcgruer raised an interesting point about "late binding". We will work on a proposal for the requirements document that the API support "late binding" which I currently undersatnd to mean that the RP can decide the concrete funding source at authentication time, and is not required to determine it at enrollment time (though that case must also be supported).

**Comment by ianbjacobs** [comment]
The API now allows the RP (or other party) to provide instrument display information at authentication time. I believe this approach renders the current issue moot, so I am going to close it. (We can reopen if I'm wrong.)
