### ISSUE TITLE
Broken "Object" xref in § Set SPC Transaction Mode

### ISSUE THREAD

**Issue by Ms2ger** [w3c/secure-payment-confirmation#203]
> If parameters is not a JSON [Object](https://w3c.github.io/FileAPI/#blob-url-entry-object)

links to the File API, which doesn't seem correct.

**Comment by stephenmcgruer** [comment]
Haha, definitely not! Nice catch, thanks :). Looks like it has been there since the [initial commit](https://github.com/w3c/secure-payment-confirmation/commit/2acc1680b964c504e3b42721668e9952248d091f), so nothing newly changed I think.

Interestingly the same thing has happened to WebAuthn, e.g. see https://w3c.github.io/webauthn/#sctn-automation-add-virtual-authenticator

We should instead link to either:

- https://w3c.github.io/webdriver/#dfn-object
- https://262.ecma-international.org/5.1/#sec-4.2.1

I can fix this today, hopefully.

**Comment by stephenmcgruer** [comment]
Also affects the Reporting API - https://w3c.github.io/reporting/#generate-test-report-command
