### ISSUE TITLE
Clarify security properties of the cryptogram

### ISSUE THREAD

**Issue by btidor-stripe** [w3c/secure-payment-confirmation#28]
The SPC spec should provide advice/a threat model on how to securely handle the cryptogram.

Questions:
* What are the requirements on the nonce (random, secret, etc.)? See #26.
* How can the cryptogram be safely verified by multiple parties (merchant, card network, issuer)?
* What data elements need to be verified in order to prevent phishing? (Is it required to verify the merchant origin, and who should do that?)
* How do we support situations where the issuer/relying party may not be invoked before the payment, e.g. Touch ID autofill?

https://lists.w3.org/Archives/Public/public-webauthn-pay/2020Sep/0009.html

**Comment by stephenmcgruer** [comment]
I think this issue is mostly answered and can be closed now:

> What are the requirements on the nonce (random, secret, etc.)?

SPC is using WebAuthn, so the [WebAuthn requirements](https://w3c.github.io/webauthn/#sctn-cryptographic-challenges) apply.

> How can the cryptogram be safely verified by multiple parties (merchant, card network, issuer)?
> What data elements need to be verified in order to prevent phishing? (Is it required to verify the merchant origin, and who should do that?)

https://w3c.github.io/secure-payment-confirmation/#sctn-verifying-assertion

> How do we support situations where the issuer/relying party may not be invoked before the payment, e.g. Touch ID autofill?

This seems out of scope for SPC currently. It's a very compelling use-case, but technically very difficult (different relying party, payment details not-yet known, etc).
