### ISSUE TITLE
Specification of the signature

### ISSUE THREAD

**Issue by tblachowicz** [w3c/secure-payment-confirmation#40]
The explainer says that 'AuthenticatorAssertionResponse.signature' will contain the signature that should be verified by the RP. WebAuthn specification has an exact signing/verifying algorithm for the signature already. In a nutshell, it is the signature over the concatenated `authenticatorData` and `clientDataJSON`. Is SPC going to overload the signing/verification algorithm to include `SecurePaymentConfirmationResponse.paymentData`? If so, it'd be great to understand the details.

**Comment by btidor-stripe** [comment]
That is the plan! At a high level, the verification algorithm mirrors [the procedure from the Web Authentication spec](https://www.w3.org/TR/webauthn-2/#sctn-verifying-assertion), with one difference: in step 12, we need to verify that the value of C.challenge equals the base64url encoding of _the SHA-256 hash of the serialized `paymentData` JSON_ instead of the traditional fixed challenge. Good question — this should definitely go in the explainer!

**Comment by tblachowicz** [comment]
@btidor-stripe: it'd be great to add the section to the explainer.

Is SPC going to also _overload_ other properties of `AuthenticatorAssertionResponse`? For example `AuthenticatorResponse.clientDataJSON` contains the following properties:

- `type`: with value either "webauthn.get" or "webauthn.create".  Woudl SPC use any od the values or should it define new value?
- `challange`: Would that value be `networkData` or hash of `paymentData`?

**Comment by cyberphone** [comment]
If the assertion involves serialized JSON objects you may run into interoperability problems since serialization of JSON objects are not guaranteed to generate stable results.  RFC8785 describes one way of dealing with such issues.

**Comment by ianbjacobs** [comment]
@tblachowicz, please review the draft API and close this issue if you are satisfied (or elaborate here any questions)

**Comment by stephenmcgruer** [comment]
Closing as I believe that this has been addressed (the signature is specified, and issue #96 covers adding Relying Party verification steps)
