### ISSUE TITLE
What happens when user cancels during transaction confirmation?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/secure-payment-confirmation#66]
Raised in discussion with @gooth:

* The transaction confirmation dialog opens.
* Instead of authenticating, the user cancels.

What does the API do? What is the UX?

**Comment by stephenmcgruer** [comment]
Unless I'm overlooking something: the API (whatever that turns out to be) returns some sort of 'abort error' (similar to https://w3c.github.io/payment-request/#dfn-user-aborts-the-payment-request for PaymentRequest) and the caller is responsible for handling that however they wish. Is there a reason to make it any more complicated?

We previously had a `fallbackUrl` concept in the explainer (https://github.com/w3c/secure-payment-confirmation/issues/57), but have not yet found concrete use-cases.

**Comment by stephenmcgruer** [comment]
I'm closing this issue as there doesn't seem to be anything to discuss here. @ianbjacobs - feel free to reopen if you think there's something.
