### ISSUE TITLE
Any browser validation of SPC input data required?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/secure-payment-confirmation#82]
Hi folks,

Assuming we have instrument information (label, icon URL) as input to an SPC API, what validation is required of the input (e.g., what happens if the label is empty?).

**Comment by stephenmcgruer** [comment]
I think this is an issue we can leave until the spec draft exists, but roughly speaking: yes, the browser will have to perform some validation :). Off the top of my head:

- `credentialIds` should probably be non-empty
- the instrument `displayName` (aka label) should probably be non-empty
- the instrument `icon` (aka icon URL) should be downloadable (that's not necessarily an immediate verification step, but failing to download would likely cause SPC to fail).

There might be other validations that are done for the WebAuthn-touching bits (though those will likely happen in WebAuthn itself anyway).

**Comment by stephenmcgruer** [comment]
So now that we have a spec draft (that I wrote), it is perhaps no surprise that the above steps are exactly the ones that I wrote down:

https://w3c.github.io/secure-payment-confirmation/#sctn-steps-to-check-if-a-payment-can-be-made

1. If request.credentialIds is empty, return false.
2. If request.instrument.displayName is empty, return false.
3. Download the image specified in request.instrument.icon. If this fails, return false.
4. Optionally, the user agent may elect to return false.
5. Return true.

Because these are part of the [steps to check if a payment can be made](https://w3c.github.io/payment-request/#dfn-steps-to-check-if-a-payment-can-be-made), then returning false means an empty handler list [here](https://w3c.github.io/payment-request/#ref-for-dfn-steps-to-check-if-a-payment-can-be-made-2), and the `show()` promise will be rejected with a NotSupported DOMException. Not the most informative error, to be fair, but passable.

As noted before, the actual call into WebAuthn should the user elect to authenticate will do additional checking, which are in the WebAuthn spec :).

I think we can probably close this, unless there were additional concrete questions?

**Comment by ianbjacobs** [comment]
@stephenmcgruer, thank you for the summary.

+1 to closing this issue. I assume there will be similar checks for any additional input data (cf issue #83; I'll add a remark there).

Should we open a new issue on "outputs"? How do the additional WebAuthn checks relate to the SPC API? How are error messages or other outputs from WebAuthn handled by SPC?

**Comment by stephenmcgruer** [comment]
> Should we open a new issue on "outputs"? How do the additional WebAuthn checks relate to the SPC API? How are error messages or other outputs from WebAuthn handled by SPC?

I don't know what this is asking for, I'm afraid. [The SPC spec says](https://w3c.github.io/secure-payment-confirmation/#sctn-steps-to-respond-to-a-payment-request) to return the promise from `navigator.credentials.get`; this promise will reject as normal for any WebAuthn failure/etc.
