### ISSUE TITLE
Popup  UI handling of origin - relying party vs. merchant

### ISSUE THREAD

**Issue by weksler** [w3c/secure-payment-confirmation#83]
The SPC popup currently shows the relying party only (e.g. adyen.com), which might be confusing to the end user, because they are transacting with the merchant (e.g. airbnb.com). Might there be a way to include that information in the SPC popup _as well_, e.g say something like ".... adyen.com on behalf of airbnb.com..." ?

**Comment by stephenmcgruer** [comment]
I believe the statement 'The SPC popup currently shows the relying party only' is incorrect, but I think I know where it is coming from.

## What we show currently

For Chrome, there are two UIs shown during authentication - the SPC transaction details dialog, and the platform-drawn WebAuthn dialog. The former currently shows the top-level domain as the 'merchant', which is automatically derived within the browser (i.e. we don't ask the caller of SPC to pass it in). The WebAuthn dialog, on the other hand, will show the relying party of the credential (e.g. the bank), as that is whom the user is authenticating to.

In the following screenshots ([demo](https://rsolomakhin.github.io/pr/spc-iframe/)):

* The 'merchant' is https://rsolomakhin.github.io/ (top-level origin)
* The 'payment service provider' is https://emerald-spiced-psychology.glitch.me/ (caller of SPC, inside an iframe)
* The 'bank' is https://lumbar-brick-soup.glitch.me/

![Screenshot 2021-06-28 154621](https://user-images.githubusercontent.com/153264/123695154-35553480-d828-11eb-8678-0fd3f095a9ae.jpg)

![Screenshot 2021-06-28 154641](https://user-images.githubusercontent.com/153264/123695434-8a914600-d828-11eb-9cae-f22fc784514f.jpg)

Notably, the payment service provider in this example is never shown to the user, but it is included in the signed cryptogram (it's the `origin` in the collected client data, IIRC). Whether it should be shown in the UI is a fair question (likely comes down to what the user agent thinks is good + what might be required for e.g. SCA compliance).

## The catch

The catch is that SPC, as currently written, **assumes the user is on the merchants web-page when it is called** (though the call itself may happen in a cross-origin subframe). That only works if iframes are being used, and what I suspect @weksler is referring to is the behavior seen when one uses a redirect model (i.e. redirects away from merchant.com to either psp.com or bank.com).

In that case, the UI will look weird, because we'll show the top-level frame as the merchant (which it clearly won't be), and the cryptogram will also contain no assertion about who the merchant is. For example, in the psp.com redirect example:

- `origin` will be psp.com
- `topOrigin` will be psp.com
- `rp` will be bank.com

## The fix...?

The 'obvious' fix is to let the caller of SPC pass in a claim about which merchant they are operating on behalf of. That would be shown in the UX, and would be included in the cryptogram in some form (note it **shouldn't** be the `origin` as that would violate the WebAuthn contract. We'd need yet another special field >_<.)

And for this obvious fix, the obvious problem is nothing stops the PSP from lying about who the merchant is. This is _probably_ fine, because what the user sees would be included in the cryptogram, and so the bank can verify that it's who they expected to pay as well (and at that point all parties are in agreement). But it definitely feels a bit... yikes. :D

**Comment by ianbjacobs** [comment]
After conversation on 12 July [1], it seems the API will support merchant identity as input in addition to topOrigin.

[1] https://www.w3.org/2021/07/12-wpwg-spc-minutes

**Comment by stephenmcgruer** [comment]
I think the only remaining question is whether there is value to keeping the (browser-determined) `topOrigin` as well as adding a new (caller-determined) `merchantOrigin`. To list values of the various members in a few scenarios

**Merchant calling SPC directly from the top-frame**:
* `origin`: merchant.com
* `topOrigin`: merchant.com
* `merchantOrigin`: merchant.com

**PSP providing SPC from within a PSP iframe**:
* `origin`: psp.com
* `topOrigin`: merchant.com
* `merchantOrigin`: merchant.com

**PSP providing SPC from a redirected page**:
* `origin`: psp.com
* `topOrigin`: psp.com
* `merchantOrigin`: merchant.com

**Bank using SPC directly in a challenge iframe**:
* `origin`: bank.com
* `topOrigin`: merchant.com
* `merchantOrigin`: merchant.com

It's probably not needed, but one argument would be yet-another layer of defense against a malicious PSP:
* `origin`: psp.com
* `topOrigin`: real-merchant.com
* `merchantOrigin`: pretending-its-this-merchant.com

**Comment by stephenmcgruer** [comment]
@rsolomakhin notes to me that there's little cost to having both, which I agree with. I'll send a PR shortly to just add `merchantOrigin` to the spec as an optional parameter to SPC auth.

**Comment by stephenmcgruer** [comment]
*Musing*: we may want to remove `topOrigin` to avoid a privacy leak whereby a cross-origin iframe could invoke SPC to discover the origin of the page they are embedded in. That is technically already available in [ancestorOrigins](https://developer.mozilla.org/en-US/docs/Web/API/Location/ancestorOrigins), but that is restricted in some cases and I believe Mozilla have also objected to it historically.

**Comment by Goosth** [comment]
Should we consider replacing the term 'merchant' with a more generic term for the receiver of the funds?
E.g. in some cases a merchant may be buying from a supplier and then this could be confusing... (the supplier is the merchant) or I'm paying a Hospital for care, or Donating to a charity or paying taxes to the government. Those are not typically 'merchants'.

Something along the lines of

  *   Creditor
  *   Payee
  *   Receiver
EMVCo and Open Banking has some standards we may want to use.

**Comment by ianbjacobs** [comment]
Payment Request uses "payee"

**Comment by ianbjacobs** [comment]
@stephenmcgruer wrote: "we may want to remove topOrigin to avoid a privacy leak whereby a cross-origin iframe could invoke SPC to discover the origin of the page they are embedded in. "

It is my understanding that SPC can only be called from a cross-origin iframe if there is permission from the surrounding context. 

In addition, I suspect payeeOrigin will be used frequently which gives nearly the same information.

In addition, signing both topOrigin and payeeOrigin could be useful for risk mitigation.

Ian
