### ISSUE TITLE
SPC Relying Party operation should be standardized

### ISSUE THREAD

**Issue by ynojima** [w3c/secure-payment-confirmation#96]
Like WebAuthn specification has "WebAuthn Relying Party Operations" section, SPC should explicitly clarify what RP has to do when verifying assertions (expecially CollectedClientPaymentData).

**Comment by stephenmcgruer** [comment]
Thanks for raising the issue: this is definitely on my TODO list :). I'm hoping to just extend the algorithm from WebAuthn (https://w3c.github.io/webauthn/#sctn-verifying-assertion) rather than repeat the entire thing (especially in case future considerations come up), but I'm aware that that may be harder for implementors to follow... :/

I'll send a PR for this issue sometime later this week.
