### ISSUE TITLE
Is the "payment" extension a part of Relying Party - Client Platform API signature?

### ISSUE THREAD

**Issue by ynojima** [w3c/secure-payment-confirmation#97]
[4.1.2](https://w3c.github.io/secure-payment-confirmation/#dom-securepaymentconfirmationrequest-extensions) states about extensions that "The caller does not need to specify the payment extension; it is added automatically", and also the payment extension doesn't output anything.
It sounds like the payment extension doesn't have relation with the "WebAuthn relying party". It seems it's just a "WebAuthn Client Platform"'s internal data structure.
If it is not a part of Relying Party - Client Platform API signature, it should not be defined in "Secure Payment Confirmation" API spec.

**Comment by ianbjacobs** [comment]
Hi @ynojima,

You wrote: "It sounds like the payment extension doesn't have relation with the "WebAuthn relying party".

However, the example in section on enrollment (1.2.1) shows the relying party referring to the "payment"
extension. So my understanding has been that the RP does come into contact with.

Does that speak to your question? (I may be reading the spec incorrectly, of course. :)

Ian

**Comment by ynojima** [comment]
Thank you for pointing out. Then, I think "payment" extension is "Registration" extension (not "Authentication" extension) and it's definition should be like this:

```
partial dictionary AuthenticationExtensionsClientInputs {
  AuthenticationExtensionsPaymentInputs payment;
};

dictionary AuthenticationExtensionsPaymentInputs {
  boolean isPayment;
};
```

**Comment by stephenmcgruer** [comment]
Hi @ynojima , and sorry for the massive delay in picking this thread back up.

I acknowledge that "payment" is a weird extension. A web developer is not allowed (i.e., the browser will throw an exception) to specify the `payment` extension in a call to `navigator.credentials.get()` directly, because we need to enforce that they go through  the [transaction confirmation UX](https://w3c.github.io/secure-payment-confirmation/#sctn-transaction-confirmation-ux). However we do have [authentication processing steps](https://w3c.github.io/secure-payment-confirmation/#client-extension-processing-authentication), and we do use the extension to [pass information](https://w3c.github.io/secure-payment-confirmation/#:~:text=Let%20payment%20be%20a%20new) into WebAuthn's `Request a Credential` algorithm (which implements `navigator.credentials.get`), so I would consider it an "Authentication" extension.

Perhaps a more important question is - does how the extension is defined matter to you for some use-case I am unaware of? In my understanding, it is just a spec artifact, a way to define a flow in a way that makes sense to implementors and also fits into the WebAuthn spec. But maybe you have a need for it to be more 'correct' for some reason?

**Comment by ianbjacobs** [comment]
@stephenmcgruer and @ynojima, 
Do you anticipate any changes to the specification regarding this issue?

**Comment by stephenmcgruer** [comment]
It is my opinion that no change is needed here, but I was still waiting to hear from the original reporter as to whether they disagree. :)

**Comment by ynojima** [comment]
@stephenmcgruer 
Sorry for overlooking your response.
If the extension is an internal data structure, which the RP doesn't need to know, I just thought it is misleading to regard it an extension, 
but I now understand the extension is needed to define the authentication processing process.
I'm OK to close this issue.

**Comment by ianbjacobs** [comment]
Thank you both!
